### ISSUE TITLE
Store GENIE and flux weights for SBNFit input

### ISSUE THREAD

**Issue by soleti** [ubneutrinos/searchingfornues#2]
We need to store the EventWeight data products for the GENIE and flux multisims. These data products are needed for systematic uncertainties evaluation and sensitivity estimate with SBNFit. Similar to what is done here: https://github.com/soleti/ElectronNeutrinoSelection/blob/74ee9476bbc76eed66cedf8937d3ea89676c0726/electronNeutrinoSelection/PandoraLEEAnalyzer_module.cc#L865

**Comment by sebprince** [comment]
Solved by merged branch
